version: "3.8"
services:
  app:
    build: .
    volumes:
      - ./keystore.p12:/app/keystore.p12
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=smartvault
      - POSTGRES_USER=smartvaultuser
      - POSTGRES_PASSWORD=123456
    ports:
      - "5433:5432"
    restart: unless-stopped
