spring:
  application:
    name: smartvault_document
  datasource:
    url: jdbc:postgresql://localhost:5432/smartvault
    username: smartvaultuser
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 3000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 25
          fetch_size: 50
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
    show-sql: false
    format_sql: false
  devtools:
    livereload:
      enabled: false
jwt:
  secret: d6734c610203dd67aa5c4d223a96b035d5f21a5d1a840e110ee0a131a67bd32d0daa2f698f8b6cfcb451065bd4793abe59a4941d51d5aaa410a056ff106dc624006249e88dba34e5a35083952184fb2eedea6044759dab1520c43db4ec17bea460749e75d107a33477007e7fec664c2b8eba253f1f2c8d864bbacd10146c08bc8faf9c7bc152ab3774fb5efbc1911cc69138cb74e3c92560e405a063843f26d4ce5e9e7ee53689b047506293882524212e8e16a42ae60d172e9433889185f376128c6913557ee9df95ea8ec29c78a032c59823adf1b3dfb5cdaaff95834097f4a87bca4fa31294deab5a30a1694e03bb4e5cbf63e0035d50985330006d1b13c3
  expirationMs: 3600000
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: true
    db:
      enabled: true
